### ISSUE TITLE
[FEATURE] Modifier les paramètres audio

### ISSUE THREAD

**Issue by DarkRewar** [Telroshan/Unity-build-settings-presets#6]
J'ai une feature request: est-ce qu'il serait possible de rajouter la possibilité d'activer et de désactiver l'audio de Unity dans les presets.
C'est notamment utile dans le cas où l'on build un serveur headless puisque, par défaut, l'audio est activé même en server build. Et donc, le moteur audio de Unity prend beaucoup de place dans la ram.

Merci 🙏

**Comment by Telroshan** [comment]
D'après [la doc "Dedicated Server optimizations"](https://docs.unity3d.com/Manual/dedicated-server-optimizations.html#AudioSubsystem), le mode serveur (headless) désactive désormais le système audio et d'autres automatiquement, donc ça devrait déjà être géré sans manip supplémentaire !

A noter que d'après le versioning de cette même doc, ça semble avoir été une nouveauté de Unity 2021
![image](https://github.com/Telroshan/Unity-build-settings-presets/assets/19146183/c857fb4e-d753-4ae3-afab-b1340c73f5ea)

Donc à partir de Unity 2021, ça devrait fonctionner _(comme ça aurait dû depuis le début, certes)_ sans modif nécessaire ici.
Je viens de publier une mise à jour pour le package, compatible Unity 2022.3 btw
